### ISSUE TITLE
로그인 페이지

### ISSUE THREAD

**Issue by iamdoerchoi** [joong8812/9kbab#1]
로그인 페이지 작성 (html, css 등)

**Comment by iamdoerchoi** [comment]
- 배경 미완성
- 회원가입페이지랑 연결 안됨
- 메인페이지랑 연결 안됨
- 아이디/패스워드 리퀘스트 작업해야함

**Comment by Augustj88** [comment]
로그인페이지 하단에 sign in 은 로그인이랑 같은 의미라 sign up으로 바꿔주면 좋을 것 같습니다.

**Comment by iamdoerchoi** [comment]
* 아이디 & 패스워드 없는 경우에도 로그인 됨

**Comment by iamdoerchoi** [comment]
완료. 추가 개선 사항 있을 시 reopen
