### ISSUE TITLE
테스트 및 버그 픽스

### ISSUE THREAD

**Issue by iamdoerchoi** [joong8812/9kbab#17]
프로젝트가 완료가 되면 모든 구성원이 테스트를 한다.
테스트 시 버그가 발견되면 해당내용을 이슈로 등록하고, 담당자 할당을 하고 고친다.

**Comment by GoHeeSeok00** [comment]
로그인 상태에서 회원가입 주소 /signup으로 접속하면 회원가입을 할 수 있는 현상이 있습니다. 

회원가입 시 쿠키여부 확인해서 로그인 상태면 메인페이지로 넘어갈 수 있게 수정하겠습니다.

**Comment by ghj99** [comment]
중복체크하고 회원가입 다음 페이지로 안 넘어감. - 해결되었음

**Comment by ghost** [comment]
회원가입 중복체크 여러번 할 때 버튼안의 텍스트가 사라집니다! ( 다시 제대로 입력했을 때 원래대로 원상복구 되기는 해요)

**Comment by GoHeeSeok00** [comment]
> 로그인 상태에서 회원가입 주소 /signup으로 접속하면 회원가입을 할 수 있는 현상이 있습니다.
> 
> 회원가입 시 쿠키여부 확인해서 로그인 상태면 메인페이지로 넘어갈 수 있게 수정하겠습니다.

수정 완료

**Comment by ghj99** [comment]
프로필 변경, 편집 페이지 아직 열리지 않음. 

게시물 삭제 기능 없음.

**Comment by iamdoerchoi** [comment]
👍
