### ISSUE TITLE
(Optional) 추가 기능 건의

### ISSUE THREAD

**Issue by iamdoerchoi** [joong8812/9kbab#20]
프로젝트 진행 상황을 보고 추가 기능을 건의 한다.
오는 금요일(1/14)까지 의견 수렴 (주말에도 개발 한다는 가정 하에...)
자유롭게 해당 이슈에 답글 부탁합니다~

**Comment by ghost** [comment]
글쓰기에 별점 들어가는 항목 있었으면 좋겠습니당 !!
