### ISSUE TITLE
로그아웃 기능 - 백엔드

### ISSUE THREAD

**Issue by iamdoerchoi** [joong8812/9kbab#21]
프론트에서 로그아웃 요청 시 토큰 제거 및 로그인 화면으로 리다이렉트

**Comment by GoHeeSeok00** [comment]
https://thalals.tistory.com/179

jwt기능은 자체 토큰 회수 기능이 없다구 하네요 ㅠ 확인부탁드려요!

**Comment by iamdoerchoi** [comment]
> 

네 해당 링크 보고 작업 완료 했습니다. 감사합니다 :)
