### ISSUE TITLE
회원가입 페이지

### ISSUE THREAD

**Issue by iamdoerchoi** [joong8812/9kbab#3]
회원가입 페이지(화면)를 만든다

**Comment by iamdoerchoi** [comment]
- 아이디, 닉네임 중복체크 작업
- 서버로 리퀘스트 작업중
- 로그인페이지 뒤로가기 작업중

**Comment by iamdoerchoi** [comment]
- 아이디, 닉네임 공백임에도 회원가입 가능.
- 회원가입 시, 비어있는 항목 경우에 따라 한번에 최대 3개 alert이 뜸 -> 순차적으로 가장 상위에 있는 공백 해당항목만 alert띄우는게 좋을 것 같음
- 아이디, 닉네임 중복체크 & 공백이 아닐 경우 회원가입 되어야함.

**Comment by Augustj88** [comment]
- 아이디, 닉네임 입력 조건 추가
- alert→<p>형식으로 추가, input입력박스 바로 아래 위치, focus명령
- 아이디, 닉네임 중복체크 후 승인, 공백은 입력조건 변경으로 입력 불가

이슈사항 수정했으나 확인 필요합니다.

**Comment by iamdoerchoi** [comment]
완료. 추가 개선 사항 있을 시 reopen
